# Generated by Django 3.2.25 on 2024-12-04 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Off',
        ),
        migrations.RenameField(
            model_name='off',
            old_name='phone',
            new_name='password',
        ),
    ]
