# Generated by Django 3.2.25 on 2024-12-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20241204_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassKey', models.CharField(max_length=10)),
            ],
        ),
    ]
