# Generated by Django 5.1.3 on 2024-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ctheft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=122)),
                ('vehicle_type', models.CharField(max_length=122)),
                ('phone_number', models.CharField(max_length=12)),
                ('number_plate_no', models.CharField(max_length=122)),
                ('rc_no', models.CharField(max_length=122)),
                ('vehicle_color', models.CharField(max_length=122)),
                ('fir_no', models.CharField(max_length=122)),
                ('additional_information', models.TextField()),
                ('date_of_theft', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
