# Generated by Django 5.1.3 on 2024-12-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ctheft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctheft',
            old_name='number_plate_no',
            new_name='number_plate',
        ),
    ]
