# Generated by Django 3.2.25 on 2024-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_number_plate_no_ctheft_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctheft',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ctheft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='ctheft',
            name='rc_no',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
