# Generated by Django 5.1.3 on 2024-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20241212_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('plate_image', models.ImageField(upload_to='plates/')),
                ('plate_number', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('car_image', models.ImageField(upload_to='cars/')),
            ],
        ),
    ]
