# Generated by Django 5.1.3 on 2024-12-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_vehicleentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleentry',
            old_name='vehicle_type',
            new_name='vehicle_id',
        ),
    ]
