# Generated by Django 3.2.25 on 2024-12-23 07:49

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_vehicle_type_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default=home.models.generate_vehicle_id, max_length=4, unique=True),
        ),
    ]
