# Generated by Django 5.1.3 on 2024-12-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_vehicleentry_vehicle_id_customuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='3962', max_length=4, unique=True),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
