# Generated by Django 5.1.3 on 2024-12-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_passwordresettoken_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='3169', max_length=4, unique=True),
        ),
    ]
