# Generated by Django 5.1.3 on 2024-12-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='5572', max_length=4, unique=True),
        ),
    ]
