# Generated by Django 3.2.25 on 2024-12-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='1151', max_length=4, unique=True),
        ),
    ]
