# Generated by Django 3.2.25 on 2025-01-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20241231_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='1651', max_length=4, unique=True),
        ),
    ]
