# Generated by Django 3.2.25 on 2025-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctheft',
            old_name='full_name',
            new_name='model_number',
        ),
        migrations.AddField(
            model_name='ctheft',
            name='owner_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='7116', max_length=4, unique=True),
        ),
    ]
