# Generated by Django 3.2.25 on 2025-01-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20250111_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctheft',
            name='owner_name',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='5731', max_length=4, unique=True),
        ),
    ]
