# Generated by Django 3.2.25 on 2025-01-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='6600', max_length=4, unique=True),
        ),
    ]
