# Generated by Django 3.2.25 on 2025-01-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='5650', max_length=4, unique=True),
        ),
    ]
