# Generated by Django 3.2.25 on 2025-02-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20250113_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='4112', max_length=4, unique=True),
        ),
    ]
