# Generated by Django 3.2.25 on 2025-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='2336', max_length=4),
        ),
    ]
