# Generated by Django 3.2.25 on 2025-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_vehicleentry_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctheft',
            name='email',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='8205', max_length=4),
        ),
    ]
