# Generated by Django 3.2.25 on 2025-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20250219_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctheft',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='5098', max_length=4),
        ),
    ]
