# Generated by Django 3.2.25 on 2025-02-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20250219_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='8927', max_length=4),
        ),
    ]
