# Generated by Django 3.2.25 on 2025-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20250219_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctheft',
            name='image',
            field=models.ImageField(blank=True, default='Not Found', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='8114', max_length=4),
        ),
    ]
