# Generated by Django 3.2.25 on 2025-02-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20250219_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='DApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('permanent_address', models.TextField()),
                ('insurance_company', models.CharField(max_length=255)),
                ('insurance_expiry', models.DateField()),
                ('vehicle_class', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('chassis_number', models.CharField(max_length=50)),
                ('engine_number', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('cubic_capacity', models.PositiveIntegerField()),
                ('cylinders', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('norms', models.CharField(max_length=50)),
                ('rc_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_id',
            field=models.CharField(default='8471', max_length=4),
        ),
    ]
